environment:
  REGISTRY: registry.scontain.com
  SCONE_VERSION: 6.1.0-rc.0
  CLI_IMAGE: registry.scontain.com/workshop/scone
  CLI_NAMESPACE: scone-tools
  CAS: cas1
  CAS_NAMESPACE: default
  VERSION: 6.0.2
  SSH_PUB_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCu9M/UuIva2A68DN29ZcXXlbW/ykeBDsqdvzBG0KrjHGtgbvI73WHU9snY3x7utnpeeWlOQabQ/ZVbs7Y3vJbAuNBepWYO5Zv6UBBrCvcJqKTi+JY0ShUhn+rLFd3/ePdapOmncJgoEr1FHslCdP3owuJsthsIUC5PPPSbJV/uWLBdMs6gsTHBwjhqjcVRmw74GbdmxRDf1MkYQqrMQwP/Mq2X/W93i6VdNbgU3bkBWJHLA8Xgj8qsnE1lelWTQ2m/eKP5HfF8el25mq5ePC/efs4cwF37t1lyEGdir0xRHHjAU7IwDsHPQaqu2HMcFhh8y/TWIYtui500uZGf8J03mNr9RmwY0TDnXnhYhFrhD/esEgxs+EbCbOk+f7CL363MsqlsPO+ojyMTyWjdLAsc4Nx2fmjYzXmFB3jSNN9JF40FR0iIDwktZk7RwPm+FviN9rmJHDIvYcD9VbQfTP4Bqllafz92MqKS+xIGucBKIC3CTBml0fk/UGRdrTGRucE8YLppdLHmIWfTrREmjR8jcPuqV6bc2xuEGhu8ivv+yLKMQhqY2MSpVsRc1QzITOLJCvEAXa6/ygdJXiYQsrT7cmh/CK86hM6jRSyl8lcmPikPnsHRUw20MYWlCyZ6v6fw3Mmb544XrlBMPn/dDZ6Zo11FPi4APsyztsvG6OQYCQ== christof.fetzer@scontain.com
