{
 "title": "SCONE Runtime Application Details Dashboard",
 "description": "Dashboard that contains metrics about the SCONE Runtime of a specific sconified app.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scone_config_id",
    "query": {
     "query": "label_values(scone_enclave_heap_allocated_bytes,scone_config_id)"
    }
   },
   {
    "name": "scone_cas_addr",
    "query": {
     "query": "label_values(scone_enclave_heap_allocated_bytes,scone_cas_addr)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(scone_enclave_heap_allocated_bytes,service)"
    }
   },
   {
    "name": "run_id",
    "query": {
     "query": "label_values(scone_enclave_heap_allocated_bytes{scone_config_id=\"$scone_config_id\", scone_cas_addr=\"$scone_cas_addr\", namespace=\"$namespace\", service=\"$service\"},run_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(scone_enclave_heap_allocated_bytes,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enclave Max Heap",
   "type": "timeseries",
   "description": "The maximal application available heap space",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scone_enclave_heap_max_bytes{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Max Heap - {{pod}}"
    }
   ]
  },
  {
   "title": "Enclave Max Allocated Heap",
   "type": "timeseries",
   "description": "The peak amount of memory requested by the application (roughly equal to VSZ)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scone_enclave_heap_allocated_bytes_max{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Max Allocated Heap - {{pod}}"
    }
   ]
  },
  {
   "title": "Enclave Allocated Heap",
   "type": "timeseries",
   "description": "The amount of memory requested by the application (roughly equal to VSZ)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scone_enclave_heap_allocated_bytes{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Allocated Heap - {{pod}}"
    }
   ]
  },
  {
   "title": "Page Allocator Calls",
   "type": "timeseries",
   "description": "Information about Page Allocator Calls.\n\nNumber of nmap() calls: Number of mmap() calls that have been handled by the in-enclave page allocator.\n\nNumber of mremap() calls: Number of mremap() calls that have been handled by the in-enclave page allocator\n\nNumber of munmap() calls: Number of munmap() calls that have been handled by the in-enclave page allocator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scone_page_allocator_mmap_calls{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Number of nmap() calls - {{pod}}"
    },
    {
     "expr": "scone_page_allocator_mremap_calls{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Number of mremap() calls - {{pod}}"
    },
    {
     "expr": "scone_page_allocator_munmap_calls{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Number of munmap() calls - {{pod}}"
    }
   ]
  },
  {
   "title": "Program Break Memory",
   "type": "timeseries",
   "description": "The size of the program break memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scone_page_allocator_brk{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Size of the Program Break Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "EDMM (Enclave Dynamic Memory Management)",
   "type": "timeseries",
   "description": "Information about the Enclave Dynamic Memory Management.\n\nCommited Heap Memory: The amount of committed heap memory (same as dynamically_allocated_memory_bytes + min_heap)\n\nDynamically Allocated Heap Memory: The amount of heap memory dynamically allocated by the application",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "scone_page_allocator_committed_memory_bytes{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Commited Heap Memory - {{pod}}"
    },
    {
     "expr": "scone_page_allocator_dynamically_allocated_memory_bytes{scone_cas_addr=\"$scone_cas_addr\", scone_config_id=\"$scone_config_id\", namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Dynamically Allocated Heap Memory - {{pod}}"
    }
   ]
  }
 ]
}