{
 "title": "SCONE Operator Controller Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# SCONE operator controller metrics\n\nThis dashboard contains metrics pertaining to the SCONE operator controller, including:\n\n* Certificate read metrics\n* Controller runtime metrics\n* Go metrics\n* Leader election metrics\n* Process metrics\n* REST client request metrics\n* Workqueue metrics"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "options": { "content": "## Certificate read metrics" } },
  {
   "title": "Certificate read errors",
   "type": "stat",
   "description": "Total number of certificate read errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "read errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "certwatcher_read_certificate_errors_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total certificate reads",
   "type": "stat",
   "description": "Total number of certificate reads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reads" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "certwatcher_read_certificate_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 }, "options": { "content": "## Controller runtime metrics" } },
  {
   "title": "Controller runtime active workers per controller",
   "type": "timeseries",
   "description": "Number of currently used workers per controller",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "workers" } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 }, "options": { "content": "### Reconciliation metrics" } },
  {
   "title": "Reconciliation errors per controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_errors_total",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation panics per controller",
   "type": "timeseries",
   "description": "Total number of reconciliation panics per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "panics" } },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_panics_total",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Terminal reconciliation errors per controller",
   "type": "timeseries",
   "description": "Total number of terminal reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "controller_runtime_terminal_reconcile_errors_total",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliations per controller",
   "type": "timeseries",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reconciliations" } },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_total\n",
     "legendFormat": "{{controller}}: {{result}}"
    }
   ]
  },
  {
   "title": "Max concurrent reconciles",
   "type": "bargauge",
   "description": "Maximum number of concurrent reconciles per controller",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reconciles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile duration - 99th percentile",
   "type": "timeseries",
   "description": "Length of time per reconciliation.\n\n99% of reconciliation operations complete within this amount of seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by (le, controller))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile duration - 50th percentile",
   "type": "timeseries",
   "description": "Length of time per reconciliation.\n\n50% of reconciliation operations complete within this amount of seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by (controller, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 69 }, "options": { "content": "### Webhoook metrics" } },
  {
   "title": "Webhook panics",
   "type": "timeseries",
   "description": "Total number of webhook panics",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "panics" } },
   "targets": [
    {
     "expr": "controller_runtime_webhook_panics_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Webhook requests in flight",
   "type": "timeseries",
   "description": "Current number of admission requests being served.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "controller_runtime_webhook_requests_in_flight",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Admission requests by HTTP status code.",
   "type": "timeseries",
   "description": "Total number of admission requests by HTTP status code.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "controller_runtime_webhook_requests_total",
     "legendFormat": "{{webhook}} - status code {{code}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 }, "options": { "content": "## Go metrics" } },
  {
   "title": "Go environment information",
   "type": "table",
   "description": "Information about the Go environment.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "targets": [
    { "expr": "go_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total goroutines",
   "type": "timeseries",
   "description": "Total number of goroutines that currently exist.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "goroutines" } },
   "targets": [
    { "expr": "sum(go_goroutines)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Go threads",
   "type": "timeseries",
   "description": "Total number of OS threads created.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    { "expr": "sum(go_threads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Garbage Collection duration",
   "type": "table",
   "description": "A summary of the pause duration of garbage collection cycles.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocated bytes in use",
   "type": "stat",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_alloc_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocated bytes (even if freed)",
   "type": "stat",
   "description": "Total number of bytes allocated, even if freed.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profiling bucket hash table bytes",
   "type": "stat",
   "description": "Number of bytes used by the profiling bucket hash table.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collection metadata bytes in use",
   "type": "stat",
   "description": "Number of bytes used for garbage collection system metadata.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_gc_sys_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last garbage collection timestamp",
   "type": "timeseries",
   "description": "Timestamp of the last garbage collection.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds * 1000",
     "legendFormat": "{{job}} on {{instance}} {{pod}} {{node}}"
    }
   ]
  },
  {
   "title": "Next garbage collection bytes",
   "type": "timeseries",
   "description": "Number of heap bytes when next garbage collection will take place.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes",
     "legendFormat": "{{job}} on {{instance}} {{node}} {{pod}}"
    }
   ]
  },
  {
   "title": "Total frees",
   "type": "stat",
   "description": "Total number of frees.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "billion frees" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_frees_total) / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lookups",
   "type": "stat",
   "description": "Total number of pointer lookups.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "lookups" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_lookups_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mallocs",
   "type": "stat",
   "description": "Total number of mallocs",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "billion mallocs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mallocs_total) / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Released heap bytes",
   "type": "stat",
   "description": "Number of heap bytes released to OS.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_released_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap bytes in use",
   "type": "stat",
   "description": "Number of heap bytes that are in use.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated heap bytes in use",
   "type": "stat",
   "description": "Number of heap bytes allocated and still in use.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle heap bytes",
   "type": "stat",
   "description": "Number of heap bytes waiting to be used.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_idle_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap system bytes",
   "type": "stat",
   "description": "Number of heap bytes obtained from system.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated heap objects",
   "type": "stat",
   "description": "Number of allocated heap objects.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "million objects" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects) / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack bytes in use",
   "type": "stat",
   "description": "Number of bytes in use by the stack allocator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_inuse_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack system bytes",
   "type": "stat",
   "description": "Number of bytes obtained from system for stack allocator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mcache structure bytes in use",
   "type": "stat",
   "description": "Number of bytes in use by mcache structures.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mcache_inuse_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mcache structure system bytes",
   "type": "stat",
   "description": "Number of bytes used for mcache structures obtained from system.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mcache_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mspan structure bytes in use",
   "type": "stat",
   "description": "Number of bytes in use by mspan structures.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mspan structure system bytes",
   "type": "stat",
   "description": "Number of bytes used for mspan structures obtained from system.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System bytes",
   "type": "stat",
   "description": "Number of bytes obtained from system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_memstats_sys_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Other system allocation bytes",
   "type": "stat",
   "description": "Number of bytes used for other system allocations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_other_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 178 }, "options": { "content": "### Process metrics" } },
  {
   "title": "Reporting system leader election status",
   "type": "stat",
   "description": "Gauge of if the reporting system is master of the relevant lease, 0 indicates backup, 1 indicates master. 'name' is the string used to identify the lease.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 180 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "leader_election_master_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "description": "Timestamp of the start time of the process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000",
     "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "CPU time spent",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total",
     "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "file descriptors" } },
   "targets": [
    {
     "expr": "process_open_fds",
     "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Maximum file descriptors",
   "type": "timeseries",
   "description": "Maximum number of open file descriptors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "file descriptors" } },
   "targets": [
    {
     "expr": "process_max_fds",
     "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Virtual memory size",
   "type": "stat",
   "description": "Virtual memory size in bytes.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum virtual memory size",
   "type": "stat",
   "description": "Maximum amount of virtual memory available in bytes.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_max_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident memory size",
   "type": "stat",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 208 },
   "options": {
    "content": "### REST client request metrics"
   }
  },
  {
   "title": "Number of HTTP requests",
   "type": "table",
   "description": "Number of HTTP requests, partitioned by status code, method, and host.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 210 },
   "targets": [
    { "expr": "rest_client_requests_total", "legendFormat": "__auto" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 223 }, "options": { "content": "### Workqueue metrics" } },
  {
   "title": "Total adds",
   "type": "timeseries",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "adds" } },
   "targets": [
    {
     "expr": "workqueue_adds_total",
     "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "retries" } },
   "targets": [
    {
     "expr": "workqueue_retries_total",
     "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "timeseries",
   "description": "Current depth of workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "targets": [
    {
     "expr": "workqueue_depth",
     "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Unfinished work duration",
   "type": "timeseries",
   "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads.\n\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds",
     "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Longest running processor time",
   "type": "timeseries",
   "description": "How many seconds has the longest running processor for workqueue been running.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds",
     "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
    }
   ]
  },
  {
   "title": "Queue duration - 99th percentile",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested.\n\n99% of items stay up to this amount of time in the workqueue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket[$__rate_interval])) by (le, name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Queue duration - 50th percentile",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested.\n\n50% of items stay up to this amount of time in the workqueue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket[$__rate_interval])) by (le, name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing duration - 99th percentile",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.\n\n99% of items stay up to this amount of time in process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket[$__rate_interval])) by (le, name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing duration - 50th percentile",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.\n\n50% of items stay up to this amount of time in process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket[$__rate_interval])) by (le, name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}