{
 "title": "SCONE Runtime Workload",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Enclave Heap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "enclave_heap_max_bytes", "legendFormat": "Max Heap" },
    {
     "expr": "enclave_heap_allocated_bytes_max",
     "legendFormat": "Max Allocated Heap"
    },
    { "expr": "enclave_heap_allocated_bytes", "legendFormat": "Allocated Heap" }
   ]
  },
  {
   "title": "Enclave Allocated Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "enclave_heap_allocated_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Page Allocator Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "page_allocator_mmap_calls", "legendFormat": "Number of mmap() calls" },
    { "expr": "page_allocator_mremap_calls", "legendFormat": "Number of mremap() calls" },
    { "expr": "page_allocator_munmap_calls", "legendFormat": "Number of munmap() calls" }
   ]
  },
  {
   "title": "Program Break Memory",
   "type": "timeseries",
   "description": "The size of the program break memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "page_allocator_brk", "legendFormat": "__auto" }
   ]
  }
 ]
}