{
 "title": "SCONE Operator CAS Details Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cas_instance",
    "query": {
     "query": "label_values(scone_cas_state{cr_namespace=~\"$namespace\"},cr_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(scone_cas_attestable,cr_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CAS metrics - $cas_instance ($namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 }, "options": { "content": "## Attestability" } },
  {
   "title": "CAS attestable",
   "type": "stat",
   "description": "This metric corresponds to the status field \"attestable\".\n\nStatus field description: The attestable state of the CAS, i.e., whether the SCONE operator could attest the CAS.\n\nThe value Yes indicates that the CAS was successfully attested.\n\nThe value No indicates that the CAS has not yet been provisioned.\n\nThe value Failed indicates that the attestation of the CAS failed.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"Failed\". The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_attestable{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS attestable",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"attestable\".\n\nStatus field description: The attestable state of the CAS, i.e., whether the SCONE operator could attest the CAS.\n\nThe value Yes indicates that the CAS was successfully attested.\n\nThe value No indicates that the CAS has not yet been provisioned.\n\nThe value Failed indicates that the attestation of the CAS failed.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"Failed\". The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "scone_cas_attestable{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "options": { "content": "## Provisioned" } },
  {
   "title": "CAS provisioned",
   "type": "stat",
   "description": "This metric corresponds to the status field \"provisioned\".\n\nStatus field description: The provisioned state of the CAS, i.e., whether the CAS is provisioned.\n\nThe value Yes indicates that the CAS is provisioned.\n\nThe value No indicates that the CAS is not provisioned.\n\n(Limitation in current implementation: Whether the CAS has been provisioned is currently determined by trying to retrieve a policy called \"provisioned\" from the CAS. On failure, the CAS is assumed to not have been provisioned. This might not be correct, in the case when the cas was indeed provisioned, but not by using the \"kubectl provision cas\" command. Using the command \"kubectl provision cas\" to provision a CAS, always creates a CAS policy called \"provisioned\".\n\nPossible metrics values: -1, 0, 1. The value -1 indicates that the metric could not be calculated. The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_provisioned{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS provisioned",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"provisioned\".\n\nStatus field description: The provisioned state of the CAS, i.e., whether the CAS is provisioned.\n\nThe value Yes indicates that the CAS is provisioned.\n\nThe value No indicates that the CAS is not provisioned.\n\n(Limitation in current implementation: Whether the CAS has been provisioned is currently determined by trying to retrieve a policy called \"provisioned\" from the CAS. On failure, the CAS is assumed to not have been provisioned. This might not be correct, in the case when the cas was indeed provisioned, but not by using the \"kubectl provision cas\" command. Using the command \"kubectl provision cas\" to provision a CAS, always creates a CAS policy called \"provisioned\".\n\nPossible metrics values: -1, 0, 1. The value -1 indicates that the metric could not be calculated. The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "scone_cas_provisioned{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 }, "options": { "content": "## Phase" } },
  {
   "title": "CAS phase",
   "type": "stat",
   "description": "This metric corresponds to the status field \"phase\". Status field description: The phase of the CAS.\n\nThe value Deleted indicates that the CAS has been deleted.\n\nThe value HEALTHY indicates that the CAS is running without any detected issues.\n\nThe value Provisioned indicates that the CAS is provisioned, its state is PENDING.\n\nThe value Unprovisioned indicates that the CAS is not provisioned.\n\nThe value EnablingMigration indicates that the CAS is provisioned but at least one node has not yet registered a backup CASes as requested.\n\nThe value Uninitialized indicates that the CAS is not provisioned and its state is PENDING.\n\nThe value AttestationFailure indicates that the CAS is provisioned but the attestation failed.\n\nThe value SnapshotFailure indicates the CAS is provisioned but its snapshots are not being performed in requested manner.\n\nThe value UNHEALTHY indicates that although the CAS is provisioned, it can be attested and its snapshots are being performed as requested, its state is UNHEALTHY. \n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"phase\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list UNHEALTHY, SnapshotFailure, AttestationFailure, EnablingMigration, Uninitialized, Unprovisioned, Provisioned, HEALTHY, Deleted.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_phase{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS phase",
   "type": "table",
   "description": "This metric corresponds to the status field \"phase\". Status field description: The phase of the CAS.\n\nThe value Deleted indicates that the CAS has been deleted.\n\nThe value HEALTHY indicates that the CAS is running without any detected issues.\n\nThe value Provisioned indicates that the CAS is provisioned, its state is PENDING.\n\nThe value Unprovisioned indicates that the CAS is not provisioned.\n\nThe value EnablingMigration indicates that the CAS is provisioned but at least one node has not yet registered a backup CASes as requested.\n\nThe value Uninitialized indicates that the CAS is not provisioned and its state is PENDING.\n\nThe value AttestationFailure indicates that the CAS is provisioned but the attestation failed.\n\nThe value SnapshotFailure indicates the CAS is provisioned but its snapshots are not being performed in requested manner.\n\nThe value UNHEALTHY indicates that although the CAS is provisioned, it can be attested and its snapshots are being performed as requested, its state is UNHEALTHY. \n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"phase\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list UNHEALTHY, SnapshotFailure, AttestationFailure, EnablingMigration, Uninitialized, Unprovisioned, Provisioned, HEALTHY, Deleted.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "scone_cas_phase{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 }, "options": { "content": "## Pod disruption budget" } },
  {
   "title": "Number of its pods that the CAS is allowing to be shut down",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"podDisruptionBudgetAlert\".\n\nStatus field description: The number of its pods that the CAS is allowing to be shutdown, for example to allow for draining a node.\n\nThe value should always be equal to 0. In case it is 1, the pod might be terminated and rescheduled on a different node.\n\nIf no nodes exist that have been registered by the CAS' backup-controller, the pod will not come up, until a node where the CAS has been registered joins the cluster.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_pod_disruption_budget_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 }, "options": { "content": "## Replica alert" } },
  {
   "title": "Number of expected CAS pods that are not running",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"replicaAlert\".\n\nStatus field description: The number of expected CAS pods that are not running. (The number of expected CAS pods is always 1.) The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_replica_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "options": { "content": "## Migration controller" } },
  {
   "title": "Number of nodes with a registered backup CAS",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"numMigratableNodes\".\n\nStatus field description: The number of nodes with a successfully registered backup CAS.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_cas_num_migratable_nodes{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Number of nodes without a registered backup CAS",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"migrationNodeAlert\".\n\nStatus field description: The number of nodes without a successfully registered backup CAS. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_cas_migration_node_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Number of expected CAS backup-controller pods that are not running",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"migrationControllerReplicaAlert\".\n\nStatus field description: The number of expected CAS backup-controller pods that are not running. (The number of expected CAS backup-controller pods is always 1.) The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_migration_controller_replica_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 }, "options": { "content": "## Safety service" } },
  {
   "title": "Safety Service Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServiceStatus\".\n\nStatus field description: The safety service status. It assumes the least healthy state between `safety_service_deployment_status` and `safety_service_pdb_status`\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Safety Service Status",
   "type": "table",
   "description": "This metric corresponds to the status field \"safetyServiceStatus\".\n\nStatus field description: The safety service status. It assumes the least healthy state between `safety_service_deployment_status` and `safety_service_pdb_status`\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Deployment Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServiceDeploymentStatus\".\n\nStatus field description: The status of the safety service deployment.\n\nThe value Healthy indicates that current number of ready replicas is equals to the desired number of replicas.\n\nThe value Alert indicates that safety service has pending replicas and ready replicas count is less than desired replicas count.\n\nThe value Unhealthy indicates that either current ready replicas count is less than spec.safetyService.minReplicas or deployment differs from spec. Also unhealthy if deployment if deployment has unavailable replicas when number of ready replicas count is not less than desired replicas count.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_deployment_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Deployment Status",
   "type": "table",
   "description": "This metric corresponds to the status field \"safetyServiceDeploymentStatus\".\n\nStatus field description: The status of the safety service deployment.\n\nThe value Healthy indicates that current number of ready replicas is equals to the desired number of replicas.\n\nThe value Alert indicates that safety service has pending replicas and ready replicas count is less than desired replicas count.\n\nThe value Unhealthy indicates that either current ready replicas count is less than spec.safetyService.minReplicas or deployment differs from spec. Also unhealthy if deployment if deployment has unavailable replicas when number of ready replicas count is not less than desired replicas count.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 67 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_deployment_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Pod Disruption Budget Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServicePDBStatus\".\n\nStatus field description: The status of the safety service pod disruption budget.\n\nThe value Healthy indicates that pod disruption budget fo the safety service is ok.\n\nThe value Alert indicates that pod disruption has no more allowed disruptions.\n\nThe value Unhealthy indicates that either the current healthy pods count is less than desired healthy pods count or pdb differs from spec.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_pdb_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Pod Disruption Budget Status",
   "type": "table",
   "description": "This metric corresponds to the status field \"safetyServicePDBStatus\".\n\nStatus field description: The status of the safety service pod disruption budget.\n\nThe value Healthy indicates that pod disruption budget fo the safety service is ok.\n\nThe value Alert indicates that pod disruption has no more allowed disruptions.\n\nThe value Unhealthy indicates that either the current healthy pods count is less than desired healthy pods count or pdb differs from spec.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 72 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_pdb_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 }, "options": { "content": "## Snapshot" } },
  {
   "title": "Snapshot Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"snapshotStatus\".\n\nStatus field description: The snapshot status of the CAS.\n\nThe value Persisted indicates that snapshots of the CAS DB are successfully being performed and saved on persistent storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == true).\n\nThe value Ephemeral indicates that snapshots of the CAS DB are successfully being performed and saved on ephemeral storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == false).\n\nThe value Initializing indicates that no snapshot of the CAS DB has been made yet but the requested snapshot interval has not yet expired.\n\nThe value Disabled indicates that cas.spec.databaseSnapshots.enabled == false and that no snapshots are being taken of the CAS DB as requested.\n\nThe value Failed indicates that the snapshots of the CAS DB are not performed as requested.\n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"snapshotStatus\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list Failed, Disabled, Initializing, Ephemeral, Persisted.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Snapshot Status",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"snapshotStatus\".\n\nStatus field description: The snapshot status of the CAS.\n\nThe value Persisted indicates that snapshots of the CAS DB are successfully being performed and saved on persistent storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == true).\n\nThe value Ephemeral indicates that snapshots of the CAS DB are successfully being performed and saved on ephemeral storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == false).\n\nThe value Initializing indicates that no snapshot of the CAS DB has been made yet but the requested snapshot interval has not yet expired.\n\nThe value Disabled indicates that cas.spec.databaseSnapshots.enabled == false and that no snapshots are being taken of the CAS DB as requested.\n\nThe value Failed indicates that the snapshots of the CAS DB are not performed as requested.\n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"snapshotStatus\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list Failed, Disabled, Initializing, Ephemeral, Persisted.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 79 },
   "targets": [
    {
     "expr": "scone_cas_snapshot_status{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Snapshot Alert",
   "type": "stat",
   "description": "A binary value indicating whether the snapshots of the CAS database are made as requested.\n\nPossible metrics values: 0, 1. The value 0 indicates success and 1 failure.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Snapshot Alert",
   "type": "timeseries",
   "description": "A binary value indicating whether the snapshots of the CAS database are made as requested.\n\nPossible metrics values: 0, 1. The value 0 indicates success and 1 failure.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 84 },
   "targets": [
    {
     "expr": "scone_cas_snapshot_alert{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Most recent CAS DB snapshot timestamp",
   "type": "stat",
   "description": "Timestamp of the most recent snapshot of the CAS DB.\n\nPossible metrics values: -1 or timestamp in seconds. -1 indicates there is no snapshot yet.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_timestamp{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS DB snapshot checked timestamp",
   "type": "stat",
   "description": "The time when the snapshot was either last performed or omitted due to lack of change of the CAS DB.\n\nPossible metrics values: -1 or timestamp in seconds. -1 indicates there is no snapshot yet.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_checked_timestamp{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot interval configured",
   "type": "stat",
   "description": "Current value of snapshot interval configured for CAS (seconds).",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_configured_interval{cr_name=\"$cas_instance\",cr_namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}