{
 "title": "SCONE Operator Dashboard",
 "description": "This dashboard contains SCONE metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cas_instance",
    "query": {
     "query": "label_values(scone_cas_state,cr_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SGXPlugin metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# SGXPlugin metrics\n\nThis section contains metrics pertaining to the SGX Plugin."
     }
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 276 }, "options": { "content": "## State" } },
    {
     "title": "SGXPlugin state",
     "type": "stat",
     "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the SGXPlugin.\n\nThe value HEALTHY indicates the SGXPlugin is running without any detected issues.\n\nThe value PENDING indicates the SGXPlugin is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1. The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".\n",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 278 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_sgxplugin_state{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "SGXPlugin state",
     "type": "timeseries",
     "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the SGXPlugin.\n\nThe value HEALTHY indicates the SGXPlugin is running without any detected issues.\n\nThe value PENDING indicates the SGXPlugin is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1. The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".\n",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 278 },
     "targets": [
      {
       "expr": "scone_sgxplugin_state{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 283 }, "options": { "content": "## SGX device usage" } },
    {
     "title": "Used SGX devices",
     "type": "stat",
     "description": "This metric monitors to the status field \"usedSGXDevices\".\n\nStatus field description: The total number of pods that has gotten access to an SGX device. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 851 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_sgxplugin_used_sgx_devices{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"} ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used SGX devices per node",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"usedSGXDevicesPerNode\".\n\nStatus field description: The number of pods that has gotten access to an SGX device on a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 851 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_used_sgx_devices_per_node",
       "legendFormat": "{{nodeName}}"
      }
     ]
    },
    {
     "title": "Allocatable (but not used) SGX devices",
     "type": "stat",
     "description": "This metric monitors to the status field \"availableSGXDevices\".\n\nStatus field description: The total number of SGX devices that are allocatable but not used. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 859 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_sgxplugin_available_sgx_devices{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocatable (but not used) SGX devices per node",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"availableSGXDevicesPerNode\".\n\nStatus field description: The number of SGX devices that are allocatable but not used at a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 859 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_available_sgx_devices_per_node",
       "legendFormat": "{{nodeName}}"
      }
     ]
    },
    {
     "title": "SGX devices capacity",
     "type": "stat",
     "description": "This metric monitors to the status field \"capacitySGXDevices\".\n\nStatus field description: The total number of SGX devices allocatable by pods. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 867 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_sgxplugin_capacity_sgx_devices{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SGX devices capacity per Node",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"capacitySGXDevicesPerNode\".\n\nStatus field description: The total number of SGX devices that can be allocated by pods on a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 867 },
     "fieldConfig": { "defaults": { "unit": "devices" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_capacity_sgx_devices_per_node",
       "legendFormat": "{{nodeName}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 875 }, "options": { "content": "## SGX-capable node metrics" } },
    {
     "title": "Number of selected SGX-capable nodes with available SGX devices",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"healthyServingReplicas\".\n\nStatus field description: The number of selected SGX-capable nodes with available SGX devices. The value -1 indicates that it could not be calculated. \n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 877 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_healthy_serving_replicas{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of selected SGX-capable nodes with no available devices in the particular device category",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"sgxDeviceAlert\".\n\nStatus field description: The number of selected SGX-capable nodes, which has no available devices in the particular device category. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 877 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_sgx_device_alert",
       "legendFormat": "{{sgxDevice}}"
      }
     ]
    },
    {
     "title": "Number of nodes on which the SGXPlugin has been selected to run",
     "type": "stat",
     "description": "This metric monitors to the status field \"desiredReplicas\".\n\nStatus field description: The number of nodes on which the SGXPlugin has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 877 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_sgxplugin_desired_replicas{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of nodes with a SGXPlugin pod in Ready state",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"readyReplicas\".\n\nStatus field description: The number of nodes with a SGXPlugin pod in Ready state. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_ready_replicas{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of SGX-capable nodes on which the SGXPlugin has been selected to run",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"servingReplicas\".\n\nStatus field description: The number of SGX-capable nodes on which the SGXPlugin has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 885 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_serving_replicas{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Ratio of selected SGX-capable nodes with available SGX devices",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"servingReplicaRatio\".\n\nStatus field description: The ratio of selected SGX-capable nodes with available SGX devices to the total of selected SGX-capable nodes (HealthyServingReplicas/ServingReplicas).\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.\n\nPossible metric values: -1, float64 between 0 and 1. The value -1 indicates that it could not be calculated.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 893 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_serving_replica_ratio{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of selected SGX-capable nodes with unavailable SGXPlugin pods",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"sgxReplicaAlert\".\n\nStatus field description: The number of selected SGX-capable nodes with unavailable SGXPlugin pods. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 893 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_sgxplugin_sgx_replica_alert{cr_name=\"sgxplugin\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LAS metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "# LAS metrics\n\nThis section contains metrics pertaining to the LAS."
     }
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 277 }, "options": { "content": "## State" } },
    {
     "title": "LAS state",
     "type": "stat",
     "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the LAS.\n\n\nThe value HEALTHY indicates the LAS is running without any detected issues.\n\nThe value PENDING indicates the LAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 279 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scone_las_state{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "LAS state",
     "type": "timeseries",
     "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the LAS.\n\n\nThe value HEALTHY indicates the LAS is running without any detected issues.\n\nThe value PENDING indicates the LAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 279 },
     "targets": [
      {
       "expr": "scone_las_state{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 850 }, "options": { "content": "## Number of nodes" } },
    {
     "title": "Number of nodes on which a LAS pod has been selected to run",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"desiredNumberScheduled\".\n\nStatus field description: The number of nodes on which a LAS pod has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 852 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_las_desired_number_scheduled{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of nodes with a LAS pod in Ready state",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"numberAvailable\".\n\nStatus field description: The number of nodes with a LAS pod in Ready state. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 852 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_las_number_available{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of expected LAS pods that are not running",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"lasReplicaAlert\".\n\nStatus field description: The number of expected LAS pods that are not running. The value -1 indicates that the metric could not be calculated or that no pods were expected to run, which is also considered erroneous.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 860 },
     "fieldConfig": { "defaults": { "unit": "nodes" } },
     "targets": [
      {
       "expr": "scone_las_las_replica_alert{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of desired replicas where the LAS probe is failing",
     "type": "timeseries",
     "description": "This metric monitors to the status field \"lasProbeAlert\".\n\nStatus field description: The number of desired replicas, where the LAS probe is failing.\n\nThe value -1 indicates that the probe could not be run (e.g., due to a pod not being ready) on at least one of the nodes.\n\nThe value 0 indicates that the LAS probe terminated successfully on all nodes. A value > 0 conveys the number of nodes on which the probe command failed, i.e., returned with a non-zero exit code.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 860 },
     "fieldConfig": { "defaults": { "unit": "replicas" } },
     "targets": [
      {
       "expr": "scone_las_las_probe_alert{cr_name=\"las\",cr_namespace=\"scone-system\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  { "title": "CAS metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "cas" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "# CAS metrics\n\nThis section contains metrics pertaining to the CAS."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 }, "options": { "content": "## Attestability" } },
  {
   "title": "CAS attestable",
   "type": "stat",
   "description": "This metric corresponds to the status field \"attestable\".\n\nStatus field description: The attestable state of the CAS, i.e., whether the SCONE operator could attest the CAS.\n\nThe value Yes indicates that the CAS was successfully attested.\n\nThe value No indicates that the CAS has not yet been provisioned.\n\nThe value Failed indicates that the attestation of the CAS failed.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"Failed\". The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_attestable{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS attestable",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"attestable\".\n\nStatus field description: The attestable state of the CAS, i.e., whether the SCONE operator could attest the CAS.\n\nThe value Yes indicates that the CAS was successfully attested.\n\nThe value No indicates that the CAS has not yet been provisioned.\n\nThe value Failed indicates that the attestation of the CAS failed.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"Failed\". The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "scone_cas_attestable{cr_name=\"$cas_instance\", namespace=\"scone-system\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "options": { "content": "## State" } },
  {
   "title": "CAS state",
   "type": "stat",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the CAS.\n\nThe value HEALTHY indicates the CAS is running without any detected issues.\n\nThe value PENDING indicates the CAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_state{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CAS state",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the CAS.\n\nThe value HEALTHY indicates the CAS is running without any detected issues.\n\nThe value PENDING indicates the CAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "scone_cas_state{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 }, "options": { "content": "## Provisioned" } },
  {
   "title": "CAS provisioned",
   "type": "stat",
   "description": "This metric corresponds to the status field \"provisioned\".\n\nStatus field description: The provisioned state of the CAS, i.e., whether the CAS is provisioned.\n\nThe value Yes indicates that the CAS is provisioned.\n\nThe value No indicates that the CAS is not provisioned.\n\n(Limitation in current implementation: Whether the CAS has been provisioned is currently determined by trying to retrieve a policy called \"provisioned\" from the CAS. On failure, the CAS is assumed to not have been provisioned. This might not be correct, in the case when the cas was indeed provisioned, but not by using the \"kubectl provision cas\" command. Using the command \"kubectl provision cas\" to provision a CAS, always creates a CAS policy called \"provisioned\".\n\nPossible metrics values: -1, 0, 1. The value -1 indicates that the metric could not be calculated. The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_provisioned{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS provisioned",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"provisioned\".\n\nStatus field description: The provisioned state of the CAS, i.e., whether the CAS is provisioned.\n\nThe value Yes indicates that the CAS is provisioned.\n\nThe value No indicates that the CAS is not provisioned.\n\n(Limitation in current implementation: Whether the CAS has been provisioned is currently determined by trying to retrieve a policy called \"provisioned\" from the CAS. On failure, the CAS is assumed to not have been provisioned. This might not be correct, in the case when the cas was indeed provisioned, but not by using the \"kubectl provision cas\" command. Using the command \"kubectl provision cas\" to provision a CAS, always creates a CAS policy called \"provisioned\".\n\nPossible metrics values: -1, 0, 1. The value -1 indicates that the metric could not be calculated. The value 0 indicates the status field value \"No\". The value 1 indicates the status field value \"Yes\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "scone_cas_provisioned{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 }, "options": { "content": "## Phase" } },
  {
   "title": "CAS phase",
   "type": "stat",
   "description": "This metric corresponds to the status field \"phase\". Status field description: The phase of the CAS.\n\nThe value Deleted indicates that the CAS has been deleted.\n\nThe value HEALTHY indicates that the CAS is running without any detected issues.\n\nThe value Provisioned indicates that the CAS is provisioned, its state is PENDING.\n\nThe value Unprovisioned indicates that the CAS is not provisioned.\n\nThe value EnablingMigration indicates that the CAS is provisioned but at least one node has not yet registered a backup CASes as requested.\n\nThe value Uninitialized indicates that the CAS is not provisioned and its state is PENDING.\n\nThe value AttestationFailure indicates that the CAS is provisioned but the attestation failed.\n\nThe value SnapshotFailure indicates the CAS is provisioned but its snapshots are not being performed in requested manner.\n\nThe value UNHEALTHY indicates that although the CAS is provisioned, it can be attested and its snapshots are being performed as requested, its state is UNHEALTHY. \n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"phase\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list UNHEALTHY, SnapshotFailure, AttestationFailure, EnablingMigration, Uninitialized, Unprovisioned, Provisioned, HEALTHY, Deleted.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_phase{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS phase",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"phase\". Status field description: The phase of the CAS.\n\nThe value Deleted indicates that the CAS has been deleted.\n\nThe value HEALTHY indicates that the CAS is running without any detected issues.\n\nThe value Provisioned indicates that the CAS is provisioned, its state is PENDING.\n\nThe value Unprovisioned indicates that the CAS is not provisioned.\n\nThe value EnablingMigration indicates that the CAS is provisioned but at least one node has not yet registered a backup CASes as requested.\n\nThe value Uninitialized indicates that the CAS is not provisioned and its state is PENDING.\n\nThe value AttestationFailure indicates that the CAS is provisioned but the attestation failed.\n\nThe value SnapshotFailure indicates the CAS is provisioned but its snapshots are not being performed in requested manner.\n\nThe value UNHEALTHY indicates that although the CAS is provisioned, it can be attested and its snapshots are being performed as requested, its state is UNHEALTHY. \n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"phase\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list UNHEALTHY, SnapshotFailure, AttestationFailure, EnablingMigration, Uninitialized, Unprovisioned, Provisioned, HEALTHY, Deleted.",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "scone_cas_phase{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 }, "options": { "content": "## Pod disruption budget" } },
  {
   "title": "Number of its pods that the CAS is allowing to be shut down",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"podDisruptionBudgetAlert\".\n\nStatus field description: The number of its pods that the CAS is allowing to be shutdown, for example to allow for draining a node.\n\nThe value should always be equal to 0. In case it is 1, the pod might be terminated and rescheduled on a different node.\n\nIf no nodes exist that have been registered by the CAS' backup-controller, the pod will not come up, until a node where the CAS has been registered joins the cluster.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_pod_disruption_budget_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 }, "options": { "content": "## Replica alert" } },
  {
   "title": "Number of expected CAS pods that are not running",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"replicaAlert\".\n\nStatus field description: The number of expected CAS pods that are not running. (The number of expected CAS pods is always 1.) The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_replica_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 }, "options": { "content": "## Migration controller" } },
  {
   "title": "Number of nodes with a registered backup CAS",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"numMigratableNodes\".\n\nStatus field description: The number of nodes with a successfully registered backup CAS.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_cas_num_migratable_nodes{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Number of nodes without a registered backup CAS",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"migrationNodeAlert\".\n\nStatus field description: The number of nodes without a successfully registered backup CAS. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_cas_migration_node_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Number of expected CAS backup-controller pods that are not running",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"migrationControllerReplicaAlert\".\n\nStatus field description: The number of expected CAS backup-controller pods that are not running. (The number of expected CAS backup-controller pods is always 1.) The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "pods" } },
   "targets": [
    {
     "expr": "scone_cas_migration_controller_replica_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 }, "options": { "content": "## Safety service" } },
  {
   "title": "Safety Service Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServiceStatus\".\n\nStatus field description: The safety service status. It assumes the least healthy state between `safety_service_deployment_status` and `safety_service_pdb_status`\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Safety Service Status",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"safetyServiceStatus\".\n\nStatus field description: The safety service status. It assumes the least healthy state between `safety_service_deployment_status` and `safety_service_pdb_status`\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 75 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Deployment Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServiceDeploymentStatus\".\n\nStatus field description: The status of the safety service deployment.\n\nThe value Healthy indicates that current number of ready replicas is equals to the desired number of replicas.\n\nThe value Alert indicates that safety service has pending replicas and ready replicas count is less than desired replicas count.\n\nThe value Unhealthy indicates that either current ready replicas count is less than spec.safetyService.minReplicas or deployment differs from spec. Also unhealthy if deployment if deployment has unavailable replicas when number of ready replicas count is not less than desired replicas count.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_deployment_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Deployment Status",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"safetyServiceDeploymentStatus\".\n\nStatus field description: The status of the safety service deployment.\n\nThe value Healthy indicates that current number of ready replicas is equals to the desired number of replicas.\n\nThe value Alert indicates that safety service has pending replicas and ready replicas count is less than desired replicas count.\n\nThe value Unhealthy indicates that either current ready replicas count is less than spec.safetyService.minReplicas or deployment differs from spec. Also unhealthy if deployment if deployment has unavailable replicas when number of ready replicas count is not less than desired replicas count.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 80 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_deployment_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Pod Disruption Budget Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"safetyServicePDBStatus\".\n\nStatus field description: The status of the safety service pod disruption budget.\n\nThe value Healthy indicates that pod disruption budget fo the safety service is ok.\n\nThe value Alert indicates that pod disruption has no more allowed disruptions.\n\nThe value Unhealthy indicates that either the current healthy pods count is less than desired healthy pods count or pdb differs from spec.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_safety_service_pdb_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Safety Service Pod Disruption Budget Status",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"safetyServicePDBStatus\".\n\nStatus field description: The status of the safety service pod disruption budget.\n\nThe value Healthy indicates that pod disruption budget fo the safety service is ok.\n\nThe value Alert indicates that pod disruption has no more allowed disruptions.\n\nThe value Unhealthy indicates that either the current healthy pods count is less than desired healthy pods count or pdb differs from spec.\n\nThe value Disabled is set when safety service is disabled.\n\nThe value Unknown is set when there current status could not be determined.\n\nPossible metrics values: -1, 0, 1, 2, 3. The value -1 indicates the status field value \"Unknown\". The value 0 indicates the status field value \"Disabled\". The value 1 indicates the status field value \"Unhealthy\". The value 2 indicates the status field value \"Alert\". The value 3 indicates the status field value \"Healthy\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 85 },
   "targets": [
    {
     "expr": "scone_cas_safety_service_pdb_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 }, "options": { "content": "## Snapshot" } },
  {
   "title": "Snapshot Status",
   "type": "stat",
   "description": "This metric corresponds to the status field \"snapshotStatus\".\n\nStatus field description: The snapshot status of the CAS.\n\nThe value Persisted indicates that snapshots of the CAS DB are successfully being performed and saved on persistent storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == true).\n\nThe value Ephemeral indicates that snapshots of the CAS DB are successfully being performed and saved on ephemeral storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == false).\n\nThe value Initializing indicates that no snapshot of the CAS DB has been made yet but the requested snapshot interval has not yet expired.\n\nThe value Disabled indicates that cas.spec.databaseSnapshots.enabled == false and that no snapshots are being taken of the CAS DB as requested.\n\nThe value Failed indicates that the snapshots of the CAS DB are not performed as requested.\n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"snapshotStatus\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list Failed, Disabled, Initializing, Ephemeral, Persisted.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Snapshot Status",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"snapshotStatus\".\n\nStatus field description: The snapshot status of the CAS.\n\nThe value Persisted indicates that snapshots of the CAS DB are successfully being performed and saved on persistent storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == true).\n\nThe value Ephemeral indicates that snapshots of the CAS DB are successfully being performed and saved on ephemeral storage as requested (i.e., cas.spec.databaseSnapshots.persistence.enabled == false).\n\nThe value Initializing indicates that no snapshot of the CAS DB has been made yet but the requested snapshot interval has not yet expired.\n\nThe value Disabled indicates that cas.spec.databaseSnapshots.enabled == false and that no snapshots are being taken of the CAS DB as requested.\n\nThe value Failed indicates that the snapshots of the CAS DB are not performed as requested.\n\nPossible metrics values: -1, a float64 between 0 and 1. The value -1 indicates that the metric could not be calculated. Otherwise, the string value of the status field \"snapshotStatus\" is mapped to a float64 value between 0 and 1, depending on the string value's index in the ordered list Failed, Disabled, Initializing, Ephemeral, Persisted.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 92 },
   "targets": [
    {
     "expr": "scone_cas_snapshot_status{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Snapshot Alert",
   "type": "stat",
   "description": "A binary value indicating whether the snapshots of the CAS database are made as requested.\n\nPossible metrics values: 0, 1. The value 0 indicates success and 1 failure.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Snapshot Alert",
   "type": "timeseries",
   "description": "A binary value indicating whether the snapshots of the CAS database are made as requested.\n\nPossible metrics values: 0, 1. The value 0 indicates success and 1 failure.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 97 },
   "targets": [
    {
     "expr": "scone_cas_snapshot_alert{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "{{__name__}} - {{cr_name}}"
    }
   ]
  },
  {
   "title": "Most recent CAS DB snapshot timestamp (since 1970)",
   "type": "stat",
   "description": "Timestamp of the most recent snapshot of the CAS DB.\n\nPossible metrics values: -1 or timestamp in seconds. -1 indicates there is no snapshot yet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_timestamp{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAS DB snapshot checked timestamp (since 1970)",
   "type": "stat",
   "description": "The time when the snapshot was either last performed or omitted due to lack of change of the CAS DB.\n\nPossible metrics values: -1 or timestamp in seconds. -1 indicates there is no snapshot yet.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_checked_timestamp{cr_name=\"$cas_instance\",cr_namespace=\"default\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot interval configured",
   "type": "stat",
   "description": "Current value of snapshot interval configured for CAS (seconds).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_snapshot_configured_interval{cr_name=\"$cas_instance\",cr_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCONE operator controller metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 545 },
     "options": {
      "content": "# SCONE operator controller metrics\n\nThis section contains metrics pertaining to the SCONE operator controller, including:\n\n* Certificate read metrics\n* Controller runtime metrics\n* Go metrics\n* Leader election metrics\n* Process metrics\n* REST client request metrics\n* Workqueue metrics"
     }
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 552 }, "options": { "content": "## Certificate read metrics" } },
    {
     "title": "Certificate read errors",
     "type": "stat",
     "description": "Total number of certificate read errors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "read errors" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "certwatcher_read_certificate_errors_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total certificate reads",
     "type": "stat",
     "description": "Total number of certificate reads",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "reads" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "certwatcher_read_certificate_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 562 }, "options": { "content": "## Controller runtime metrics" } },
    {
     "title": "Controller runtime active workers per controller",
     "type": "timeseries",
     "description": "Number of currently used workers per controller",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 564 },
     "fieldConfig": { "defaults": { "unit": "workers" } },
     "targets": [
      {
       "expr": "controller_runtime_active_workers",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 572 }, "options": { "content": "### Reconciliation metrics" } },
    {
     "title": "Reconciliation errors per controller",
     "type": "timeseries",
     "description": "Total number of reconciliation errors per controller",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 574 },
     "fieldConfig": { "defaults": { "unit": "errors" } },
     "targets": [
      {
       "expr": "controller_runtime_reconcile_errors_total",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconciliation panics per controller",
     "type": "timeseries",
     "description": "Total number of reconciliation panics per controller",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 574 },
     "fieldConfig": { "defaults": { "unit": "panics" } },
     "targets": [
      {
       "expr": "controller_runtime_reconcile_panics_total",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Terminal reconciliation errors per controller",
     "type": "timeseries",
     "description": "Total number of terminal reconciliation errors per controller",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 582 },
     "fieldConfig": { "defaults": { "unit": "errors" } },
     "targets": [
      {
       "expr": "controller_runtime_terminal_reconcile_errors_total",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconciliations per controller",
     "type": "timeseries",
     "description": "Total number of reconciliations per controller",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 582 },
     "fieldConfig": { "defaults": { "unit": "reconciliations" } },
     "targets": [
      {
       "expr": "controller_runtime_reconcile_total\n",
       "legendFormat": "{{controller}}: {{result}}"
      }
     ]
    },
    {
     "title": "Max concurrent reconciles",
     "type": "bargauge",
     "description": "Maximum number of concurrent reconciles per controller",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 590 },
     "fieldConfig": { "defaults": { "unit": "reconciles" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "controller_runtime_max_concurrent_reconciles",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconcile duration - 99th percentile",
     "type": "timeseries",
     "description": "Length of time per reconciliation.\n\n99% of reconciliation operations complete within this amount of seconds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 598 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by (le, controller))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reconcile duration - 50th percentile",
     "type": "timeseries",
     "description": "Length of time per reconciliation.\n\n50% of reconciliation operations complete within this amount of seconds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 606 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by (controller, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 614 }, "options": { "content": "### Webhoook metrics" } },
    {
     "title": "Webhook panics",
     "type": "timeseries",
     "description": "Total number of webhook panics",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "panics" } },
     "targets": [
      {
       "expr": "controller_runtime_webhook_panics_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Webhook requests in flight",
     "type": "timeseries",
     "description": "Current number of admission requests being served.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "requests" } },
     "targets": [
      {
       "expr": "controller_runtime_webhook_requests_in_flight",
       "legendFormat": "{{webhook}}"
      }
     ]
    },
    {
     "title": "Admission requests by HTTP status code.",
     "type": "timeseries",
     "description": "Total number of admission requests by HTTP status code.",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "requests" } },
     "targets": [
      {
       "expr": "controller_runtime_webhook_requests_total",
       "legendFormat": "{{webhook}} - status code {{code}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 632 }, "options": { "content": "## Go metrics" } },
    {
     "title": "Go environment information",
     "type": "table",
     "description": "Information about the Go environment.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 634 },
     "targets": [
      { "expr": "go_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total goroutines",
     "type": "timeseries",
     "description": "Total number of goroutines that currently exist.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 646 },
     "fieldConfig": { "defaults": { "unit": "goroutines" } },
     "targets": [
      { "expr": "sum(go_goroutines)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Go threads",
     "type": "timeseries",
     "description": "Total number of OS threads created.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 646 },
     "fieldConfig": { "defaults": { "unit": "threads" } },
     "targets": [
      { "expr": "sum(go_threads)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Garbage Collection duration",
     "type": "table",
     "description": "A summary of the pause duration of garbage collection cycles.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 654 },
     "targets": [
      { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Allocated bytes in use",
     "type": "stat",
     "description": "Number of bytes allocated and still in use.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 670 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(go_memstats_alloc_bytes)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Allocated bytes (even if freed)",
     "type": "stat",
     "description": "Total number of bytes allocated, even if freed.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 670 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_alloc_bytes_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Profiling bucket hash table bytes",
     "type": "stat",
     "description": "Number of bytes used by the profiling bucket hash table.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 670 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_buck_hash_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Garbage collection metadata bytes in use",
     "type": "stat",
     "description": "Number of bytes used for garbage collection system metadata.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 670 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(go_memstats_gc_sys_bytes)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Time since last garbage collection (since 1970)",
     "type": "timeseries",
     "description": "Number of seconds since 1970 of last garbage collection.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 678 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds",
       "legendFormat": "{{job}} on {{instance}} {{pod}} {{node}}"
      }
     ]
    },
    {
     "title": "Next garbage collection bytes",
     "type": "timeseries",
     "description": "Number of heap bytes when next garbage collection will take place.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 678 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes",
       "legendFormat": "{{job}} on {{instance}} {{node}} {{pod}}"
      }
     ]
    },
    {
     "title": "Total frees",
     "type": "stat",
     "description": "Total number of frees.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "billion frees" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_frees_total) / 1e9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lookups",
     "type": "stat",
     "description": "Total number of pointer lookups.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "lookups" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(go_memstats_lookups_total)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Mallocs",
     "type": "stat",
     "description": "Total number of mallocs",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "billion mallocs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_mallocs_total) / 1e9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Released heap bytes",
     "type": "stat",
     "description": "Number of heap bytes released to OS.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 686 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_released_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap bytes in use",
     "type": "stat",
     "description": "Number of heap bytes that are in use.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 694 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_inuse_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated heap bytes in use",
     "type": "stat",
     "description": "Number of heap bytes allocated and still in use.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 694 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_alloc_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Idle heap bytes",
     "type": "stat",
     "description": "Number of heap bytes waiting to be used.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 694 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_idle_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap system bytes",
     "type": "stat",
     "description": "Number of heap bytes obtained from system.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 694 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Allocated heap objects",
     "type": "stat",
     "description": "Number of allocated heap objects.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 702 },
     "fieldConfig": { "defaults": { "unit": "million objects" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_objects) / 1e6",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stack bytes in use",
     "type": "stat",
     "description": "Number of bytes in use by the stack allocator.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 710 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_stack_inuse_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stack system bytes",
     "type": "stat",
     "description": "Number of bytes obtained from system for stack allocator.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 710 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_stack_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mcache structure bytes in use",
     "type": "stat",
     "description": "Number of bytes in use by mcache structures.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 718 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_mcache_inuse_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mcache structure system bytes",
     "type": "stat",
     "description": "Number of bytes used for mcache structures obtained from system.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 718 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_mcache_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mspan structure bytes in use",
     "type": "stat",
     "description": "Number of bytes in use by mspan structures.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 718 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_mspan_inuse_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mspan structure system bytes",
     "type": "stat",
     "description": "Number of bytes used for mspan structures obtained from system.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 718 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_mspan_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System bytes",
     "type": "stat",
     "description": "Number of bytes obtained from system.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 726 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(go_memstats_sys_bytes)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Other system allocation bytes",
     "type": "stat",
     "description": "Number of bytes used for other system allocations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 726 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_memstats_other_sys_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 734 }, "options": { "content": "### Process metrics" } },
    {
     "title": "Reporting system leader election status",
     "type": "stat",
     "description": "Gauge of if the reporting system is master of the relevant lease, 0 indicates backup, 1 indicates master. 'name' is the string used to identify the lease.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 736 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "leader_election_master_status", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Start time (since 1970)",
     "type": "timeseries",
     "description": "Start time of the process since UNIX epoch in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 744 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "process_start_time_seconds",
       "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "CPU time spent",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 744 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "process_cpu_seconds_total",
       "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 752 },
     "fieldConfig": { "defaults": { "unit": "file descriptors" } },
     "targets": [
      {
       "expr": "process_open_fds",
       "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Maximum file descriptors",
     "type": "timeseries",
     "description": "Maximum number of open file descriptors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 752 },
     "fieldConfig": { "defaults": { "unit": "file descriptors" } },
     "targets": [
      {
       "expr": "process_max_fds",
       "legendFormat": "{{job}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Virtual memory size",
     "type": "stat",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 760 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Maximum virtual memory size",
     "type": "stat",
     "description": "Maximum amount of virtual memory available in bytes.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 760 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_virtual_memory_max_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resident memory size",
     "type": "stat",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 760 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 768 },
     "options": {
      "content": "### REST client request metrics"
     }
    },
    {
     "title": "Number of HTTP requests",
     "type": "table",
     "description": "Number of HTTP requests, partitioned by status code, method, and host.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 770 },
     "targets": [
      { "expr": "rest_client_requests_total", "legendFormat": "__auto" }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 786 }, "options": { "content": "### Workqueue metrics" } },
    {
     "title": "Total adds",
     "type": "timeseries",
     "description": "Total number of adds handled by workqueue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "adds" } },
     "targets": [
      {
       "expr": "workqueue_adds_total",
       "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Total retries",
     "type": "timeseries",
     "description": "Total number of retries handled by workqueue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "retries" } },
     "targets": [
      {
       "expr": "workqueue_retries_total",
       "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Workqueue depth",
     "type": "timeseries",
     "description": "Current depth of workqueue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 796 },
     "targets": [
      {
       "expr": "workqueue_depth",
       "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Unfinished work duration",
     "type": "timeseries",
     "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads.\n\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 796 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "workqueue_unfinished_work_seconds",
       "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Longest running processor time",
     "type": "timeseries",
     "description": "How many seconds has the longest running processor for workqueue been running.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 804 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "workqueue_longest_running_processor_seconds",
       "legendFormat": "{{name}} - {{endpoint}} on {{instance}}{{metrics_path}}  {{node}}"
      }
     ]
    },
    {
     "title": "Queue duration - 99th percentile",
     "type": "timeseries",
     "description": "How long in seconds an item stays in workqueue before being requested.\n\n99% of items stay up to this amount of time in the workqueue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 812 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket[$__rate_interval])) by (le, name))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Queue duration - 50th percentile",
     "type": "timeseries",
     "description": "How long in seconds an item stays in workqueue before being requested.\n\n50% of items stay up to this amount of time in the workqueue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 812 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket[$__rate_interval])) by (le, name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing duration - 99th percentile",
     "type": "timeseries",
     "description": "How long in seconds processing an item from workqueue takes.\n\n99% of items stay up to this amount of time in process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket[$__rate_interval])) by (le, name))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processing duration - 50th percentile",
     "type": "timeseries",
     "description": "How long in seconds processing an item from workqueue takes.\n\n50% of items stay up to this amount of time in process.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 820 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket[$__rate_interval])) by (le, name))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}