{
 "title": "SCONE Operator Dashboard",
 "description": "This dashboard contains SCONE metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cas_instance",
    "query": {
     "query": "label_values(scone_cas_state,cr_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SGXPlugin metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# SGXPlugin metrics\n\nThis section contains metrics pertaining to the SGX Plugin."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 }, "options": { "content": "## State" } },
  {
   "title": "SGXPlugin state",
   "type": "stat",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the SGXPlugin.\n\nThe value HEALTHY indicates the SGXPlugin is running without any detected issues.\n\nThe value PENDING indicates the SGXPlugin is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1. The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".\n",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_state{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "SGXPlugin state",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the SGXPlugin.\n\nThe value HEALTHY indicates the SGXPlugin is running without any detected issues.\n\nThe value PENDING indicates the SGXPlugin is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1. The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".\n",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "scone_sgxplugin_state{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 }, "options": { "content": "## SGX device usage" } },
  {
   "title": "Used SGX devices",
   "type": "stat",
   "description": "This metric monitors to the status field \"usedSGXDevices\".\n\nStatus field description: The total number of pods that has gotten access to an SGX device. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_used_sgx_devices{cr_name=\"sgxplugin\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used SGX devices per node",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"usedSGXDevicesPerNode\".\n\nStatus field description: The number of pods that has gotten access to an SGX device on a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_used_sgx_devices_per_node",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "Allocatable (but not used) SGX devices",
   "type": "stat",
   "description": "This metric monitors to the status field \"availableSGXDevices\".\n\nStatus field description: The total number of SGX devices that are allocatable but not used. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_available_sgx_devices{cr_name=\"sgxplugin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocatable (but not used) SGX devices per node",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"availableSGXDevicesPerNode\".\n\nStatus field description: The number of SGX devices that are allocatable but not used at a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_available_sgx_devices_per_node",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  {
   "title": "SGX devices capacity",
   "type": "stat",
   "description": "This metric monitors to the status field \"capacitySGXDevices\".\n\nStatus field description: The total number of SGX devices allocatable by pods. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_capacity_sgx_devices{cr_name=\"sgxplugin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGX devices capacity per Node",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"capacitySGXDevicesPerNode\".\n\nStatus field description: The total number of SGX devices that can be allocated by pods on a node. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_capacity_sgx_devices_per_node",
     "legendFormat": "{{nodeName}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 }, "options": { "content": "## SGX-capable node metrics" } },
  {
   "title": "Number of selected SGX-capable nodes with available SGX devices",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"healthyServingReplicas\".\n\nStatus field description: The number of selected SGX-capable nodes with available SGX devices. The value -1 indicates that it could not be calculated. \n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_healthy_serving_replicas{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of selected SGX-capable nodes with no available devices in the particular device category",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"sgxDeviceAlert\".\n\nStatus field description: The number of selected SGX-capable nodes, which has no available devices in the particular device category. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_sgx_device_alert",
     "legendFormat": "{{sgxDevice}}"
    }
   ]
  },
  {
   "title": "Number of nodes on which the SGXPlugin has been selected to run",
   "type": "stat",
   "description": "This metric monitors to the status field \"desiredReplicas\".\n\nStatus field description: The number of nodes on which the SGXPlugin has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_desired_replicas{cr_name=\"sgxplugin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of nodes with a SGXPlugin pod in Ready state",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"readyReplicas\".\n\nStatus field description: The number of nodes with a SGXPlugin pod in Ready state. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_ready_replicas{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of SGX-capable nodes on which the SGXPlugin has been selected to run",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"servingReplicas\".\n\nStatus field description: The number of SGX-capable nodes on which the SGXPlugin has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_serving_replicas{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Ratio of selected SGX-capable nodes with available SGX devices",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"servingReplicaRatio\".\n\nStatus field description: The ratio of selected SGX-capable nodes with available SGX devices to the total of selected SGX-capable nodes (HealthyServingReplicas/ServingReplicas).\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.\n\nPossible metric values: -1, float64 between 0 and 1. The value -1 indicates that it could not be calculated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_serving_replica_ratio{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of selected SGX-capable nodes with unavailable SGXPlugin pods",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"sgxReplicaAlert\".\n\nStatus field description: The number of selected SGX-capable nodes with unavailable SGXPlugin pods. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_sgxplugin_sgx_replica_alert{cr_name=\"sgxplugin\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "LAS metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "# LAS metrics\n\nThis section contains metrics pertaining to the LAS."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 }, "options": { "content": "## State" } },
  {
   "title": "LAS state",
   "type": "stat",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the LAS.\n\n\nThe value HEALTHY indicates the LAS is running without any detected issues.\n\nThe value PENDING indicates the LAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_las_state{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "LAS state",
   "type": "timeseries",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the LAS.\n\n\nThe value HEALTHY indicates the LAS is running without any detected issues.\n\nThe value PENDING indicates the LAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 69 },
   "targets": [
    {
     "expr": "scone_las_state{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 }, "options": { "content": "## Number of nodes" } },
  {
   "title": "Number of nodes on which a LAS pod has been selected to run",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"desiredNumberScheduled\".\n\nStatus field description: The number of nodes on which a LAS pod has been selected to run. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_las_desired_number_scheduled{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of nodes with a LAS pod in Ready state",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"numberAvailable\".\n\nStatus field description: The number of nodes with a LAS pod in Ready state. The value -1 indicates that it could not be calculated.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_las_number_available{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of expected LAS pods that are not running",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"lasReplicaAlert\".\n\nStatus field description: The number of expected LAS pods that are not running. The value -1 indicates that the metric could not be calculated or that no pods were expected to run, which is also considered erroneous.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "scone_las_las_replica_alert{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of desired replicas where the LAS probe is failing",
   "type": "timeseries",
   "description": "This metric monitors to the status field \"lasProbeAlert\".\n\nStatus field description: The number of desired replicas, where the LAS probe is failing.\n\nThe value -1 indicates that the probe could not be run (e.g., due to a pod not being ready) on at least one of the nodes.\n\nThe value 0 indicates that the LAS probe terminated successfully on all nodes. A value > 0 conveys the number of nodes on which the probe command failed, i.e., returned with a non-zero exit code.\n\nPossible metrics values: The value of this metric is always equal to the value of the status field.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "replicas" } },
   "targets": [
    {
     "expr": "scone_las_las_probe_alert{cr_name=\"las\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "CAS metrics overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }, "repeat": "cas" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 93 },
   "options": {
    "content": "# CAS metrics overview\n\nThis section provides an overview of the states of all CAS instances. In order to view detailed metrics for a specific CAS instance, please click on the value of its corresponding state metric."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 96 }, "options": { "content": "## State" } },
  {
   "title": "CAS state",
   "type": "table",
   "description": "This metric corresponds to the status field \"state\".\n\nStatus field description: The state of the CAS.\n\nThe value HEALTHY indicates the CAS is running without any detected issues.\n\nThe value PENDING indicates the CAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention.\n\nThe value UNHEALTHY indicates a problem has been detected.\n\nPossible metrics values: -1, 0, 1.  The value -1 indicates the status field value \"UNHEALTHY\". The value 0 indicates the status field value \"PENDING\". The value 1 indicates the status field value \"HEALTHY\".",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 98 },
   "targets": [
    { "expr": "scone_cas_state", "legendFormat": "{{cr_name}} ({{cr_namespace}})" }
   ]
  }
 ]
}