#!/usr/bin/env bash

set -euo pipefail 
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF
# 'golang' Confidential Computing Support

We show how to build native Go-based binaries that can be used in the context of confidential computing. Note that the compiled binaries are native libraries without any code related to confidential computing. The only difference is that the binaries are linked with a 'libc' (see below). 

We show how to compile Go programs that can later inside Trusted Execution Environments (TEEs): 

- Intel SGX enclaves,
- Intel TDX CVMs (Confidential VMs), or
- AMD SEV SNP CVMs.

This documentation is an adaptation of this page: https://hub.docker.com/_/golang


## What is Go?

'Go' (a.k.a., 'Golang') is a programming language first developed at Google. It is a statically-typed language with syntax loosely derived from C, but with additional features such as garbage collection, type safety, some dynamic-typing capabilities, additional built-in types (e.g., variable-length arrays and key-value maps), and a large standard library. For more details, please see [wikipedia](https://en.wikipedia.org/wiki/Go_(programming_language)).

## Why use different Go images for confidential computing?

To minimize the TCB (Trusted Computing Base), we attest and isolate each microservice individually using either Intel SGX or some isolation mechanism within the CVM. In this way, we can keep the keys and the data of application secret even against adversaries that have gained access to the (C)VM in which the application is running.

To isolate an application, we intercept system calls. To have reasonable performance, we intercept the system calls at the 'libc' level. The golang compiler - unlike other programming languages like 'Java' or 'Rust' - issues system calls directly without using a 'libc'. To solve this problem, we minimally patch the upstream 'Go' compiler:


> We use the original base images from Docker Hub and patch these to use 'glibc' (for Debian / Ubuntu) or 'musl' libs (Alpine Linux) to issue system calls.
> The generated programs are otherwise identical to the programs generated by the original 'golang' compiler.

We provide the following images:


| **golang**:**original tag** | registry.scontain.com/scone.cloud/:**pushed tags** |
|---|---|
| '1.24.2-bookworm' | '1.24.2-bookworm', '1', '1.24', '1.24.2', '1.24-bookworm', '1-bookworm', 'bookworm' |
| '1.24.2-alpine3.21' | '1.24.2-alpine3.21', '1.24-alpine3.21', '1-alpine3.21', 'alpine3.21', '1.24.2-alpine', '1.24-alpine', '1-alpine', 'alpine' |
| '1.23.8-bullseye' | '1.23.8-bullseye' |
| '1.23.8-bookworm' | '1.23.8-bookworm' |
| '1.23.8-alpine3.21' | '1.23.8-alpine3.21' |
| '1.22.12-bookworm' | '1.22.12-bookworm' |
| '1.22.12-alpine3.21' | '1.22.12-alpine3.21' |
| '1.22.5-bullseye' | '1.22.5-bullseye' |
| '1.22.5-alpine3.20' | '1.22.5-alpine3.20' |
| '1.20.5-alpine3.18' | '1.20.5-alpine3.18' |


All images are signed and the images can be verified with 'cosign' using the following key:

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErLf0HT8xZlLaoX5jNN8aVL1Yrs+P
wS7K6tXeRlWLlUX1GeEtTdcuhZMKb5VUNaWEJW2ZU0YIF91D93dCZbUYpw==
-----END PUBLIC KEY-----

## How to use the Go images

The images can be used in exactly the same way as the original images on Docker Hub. Hence, the remainder of this documentation is a copy of <https://hub.docker.com/_/golang>

Note: '/go' is world-writable to allow flexibility in the user which runs the container (for example, in a container started with '-'-user 1000:1000, running 'go get github.com/example/...' into the default '\$GOPATH' will succeed). While the '777' directory would be insecure on a regular host setup, there are not typically other processes or users inside the container, so this is equivalent to '700' for Docker usage, but allowing for '--user' flexibility.


## Start a Go instance in your app

The most straightforward way to use this image is to use a Go container as both the build and runtime environment. In your Dockerfile, writing something along the lines of the following will compile and run your project (assuming it uses go.mod for dependency management):

EOF
printf "${RESET}"

cd go-example

cat > Dockerfile <<EOF
FROM registry.scontain.com/scone.cloud/golang:1.24

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

CMD ["app"]
EOF
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

You can then build and run the Docker image:

EOF
printf "${RESET}"

docker build -f Dockerfile -t my-golang-app .
docker run -it --rm --name my-running-app my-golang-app
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

# Compile your app inside the Docker container

There may be occasions where it is not appropriate to run your app inside a container. To compile, but not run your app inside the Docker instance, you can write something like:

EOF
printf "${RESET}"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp registry.scontain.com/scone.cloud/golang:1.24 go build -v
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

This will add your current directory as a volume to the container, set the working directory to the volume, and run the command go build which will tell go to compile the project in the working directory and output the executable to myapp. Alternatively, if you have a Makefile, you can run the make command inside your container.

EOF
printf "${RESET}"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp registry.scontain.com/scone.cloud/golang:1.24 make build
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

Cross-compile your app inside the Docker container
If you need to compile your application for a platform other than linux/amd64 (such as windows/386):

EOF
printf "${RESET}"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e GOOS=windows -e GOARCH=386 registry.scontain.com/scone.cloud/golang:1.24 go build -v
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

Alternatively, you can build for multiple platforms at once:

EOF
printf "${RESET}"

mkdir -p bin
docker run --rm -it -v "$PWD":/usr/src/myapp -w /usr/src/myapp registry.scontain.com/scone.cloud/golang:1.24 bash -lc '\
	    set -euo pipefail; \
	    for GOOS in linux; do \
	      for GOARCH in 386 amd64; do \
	        out="bin/go-args-env-file-${GOOS}-${GOARCH}"; \
	        GOOS=$GOOS GOARCH=$GOARCH /usr/local/go/bin/go build -v -o "$out" .; \
	      done; \
	    done'
LILAC='\033[1;35m'
RESET='\033[0m'
printf "${LILAC}"
cat <<EOF

### Git LFS

If downloading your dependencies results in an error like "checksum mismatch", you should check whether they are using Git LFS⁠ (and thus need it installed for downloading them and calculating correct go.sum values).

## Image Variants

The golang images come in many flavors, each designed for a specific use case.

### 'registry.scontain.com/scone.cloud/golang:<version>'

This is the defacto image. If you are unsure about what your needs are, you probably want to use this one. It is designed to be used both as a throw away container (mount your source code and start the container to start your app), as well as the base to build other images off of.

Some of these tags may have names like bookworm or bullseye in them. These are the suite code names for releases of Debian⁠ and indicate which release the image is based on. If your image needs to install any additional packages beyond what comes with the image, you'll likely want to specify one of these explicitly to minimize breakage when there are new releases of Debian.

### 'registry.scontain.com/scone.cloud/golang:<version>-alpine'

This image is based on the popular Alpine Linux project⁠, available in the alpine official image. Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.

This variant is highly experimental, and not officially supported by the Go project (see golang/go#19938⁠ for details).

The main caveat to note is that it does use musl libc⁠ instead of glibc and friends⁠, which can lead to unexpected behavior. See this Hacker News comment thread⁠ for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

To minimize image size, additional related tools (such as git, gcc, or bash) are not included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar). See also docker-library/golang#250 (comment)⁠ for a longer explanation.

## License

[View license](https://go.dev/LICENSE) information⁠ for the software contained in this image.

As with all Docker images, these likely also contain other software which may be under other licenses (such as 'Bash', 'musl', or 'glibc', etc from the base distribution, along with any direct or indirect dependencies of the primary software being contained).

Some additional license information which was able to be auto-detected might be found in the repo-info repository's 'golang/' directory⁠.

As for any pre-built image usage, it is the image user's responsibility to ensure that any use of this image complies with any relevant licenses for all software contained within.
EOF
printf "${RESET}"

